### PR TITLE
Fixed dispatchNow method according to Dispatcher contract

### PR DESCRIPTION
**Pull request by DeRain**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
That change won't work. That param does something very different.

**Comment by GrahamCampbell** [comment]
This package is obsolete in 5.3.

**Comment by DeRain** [comment]
@GrahamCampbell does we have any alternatives for 5.3?

**Comment by GrahamCampbell** [comment]
Yes. See the PR that was sent to the core, or I have a package alt-three/bus which mimics 5.1 syntax on 5.3.

**Pull request closed without merging**
