### PR TITLE
Dev fix dispatcher override.

### PR DESCRIPTION
**Pull request by bakome**
Fix Dispatcher dispatchNow method override error not compatibile with laravel 5.3 dispatchNow method when overriding

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This isn't the correct fix.

**Comment by bakome** [comment]
Can you help with the correct fix. As i see before incorrect fix Liskov substitution principle was ruined.

**Comment by GrahamCampbell** [comment]
My solution was just to use the package I made that actually works on L5.3: https://github.com/AltThree/Bus/

**Comment by GrahamCampbell** [comment]
Far less invasive than this one too: https://github.com/AltThree/Bus/blob/master/src/Dispatcher.php.

**Comment by bakome** [comment]
Thanks.

**Comment by gvlatko** [comment]
how is this not the correct fix?
and how is forcing another package on top the solution?

**Comment by lindyhopchris** [comment]
Totally agree. if this package is tagged as `v5.3.0` (which it has) - but it doesn't actually work - then `v5.3.1` needs to be released fixing the problem.

Either that, or remove the `v5.3.0` tag and deprecate the package - pointing people to the new package for Laravel 5.3 applications. 

But at the moment your `composer.json` says it can be installed with Laravel 5.3 but it can't.

**Comment by GrahamCampbell** [comment]
Should be deprecated imo.

**Comment by gvlatko** [comment]
No. It should be patched and released because it's a complete package.

**Comment by GrahamCampbell** [comment]
This patch is incorrect and doesn;t work. it's not even needed in laravel 5.3 really anyway

**Comment by GrahamCampbell** [comment]
I made a package which brings L5.1 similarities to the new L5.3 bus: https://github.com/AltThree/Bus.

**Comment by gvlatko** [comment]
Let me reply to your package with your own quote:
" it's not even needed in laravel 5.3 really anyway"

**Comment by GrahamCampbell** [comment]
> " it's not even needed in laravel 5.3 really anyway"

It's not needed really, certainly not in this form. This package is totally unsuitable for usage in L5.3.

The alt three package is a total replacement, zero code in common with this package.

**Comment by gvlatko** [comment]
That's exactly why i need the collective package and not yours.

On Nov 15, 2016 21:36, "Graham Campbell" notifications@github.com wrote:

" it's not even needed in laravel 5.3 really anyway"

It's not needed really, certainly not in this form. This package is totally
unsuitable for usage in L5.3.

The alt three package is a total replacement, zero code in common with this
package.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
https://github.com/LaravelCollective/bus/pull/14#issuecomment-260760014,
or mute the thread

**Comment by GrahamCampbell** [comment]
The collective package is not needed on L5.3. Do you not see why?

**Comment by gvlatko** [comment]
It's like talking to a parrot...

**Comment by GrahamCampbell** [comment]
Well, I could say the same. Unsubscribing from this thread. We already bothered to implement a solution in the core. What more can we do.

**Comment by mlantz** [comment]
Hey all, sorry about this, will merge in the fix and move this forward, @GrahamCampbell I appreciate all the help I can get on this I don't know much about the Bus but I'm trying to help move the ball forward.

**Comment by GrahamCampbell** [comment]
This **IS NOT** a fix. It **DOES NOT** actually work. All it does is pretends to fix the real interface problem.

**Pull request closed without merging**
